"use client"

import { useState } from 'react';
import Cart from './components/Cart';
import Navbar from './components/Navbar';
import './globals.css'
import "cal-sans";
import { CartProvider } from "react-use-cart";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const [open, setOpen] = useState(false)
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Cart open={open} setOpen={setOpen}/>
          <Navbar open={open} setOpen={setOpen}/>
          {children}
        </CartProvider>
      </body>
    </html>
  )
}
